services:
  service1: 
    build: 
      context: ./service-1
    ports:
      - "3000:3000"
  nginx:
    image: nginx:alpine
    container_name: nginx
    ports:  
      - "81:80"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - service1  