services:
  nextjs-app:
    container_name: nextjs-app
    build: 
      context: .
      dockerfile: Dockerfile
    ports:
      - "81:80"
    volumes:
      - .:/app
      - /app/node_modules
    networks:
      - app_network

networks:
  app_network:
    external: true
