version: '3'

services:
  nextjs:
    build: .
    container_name: nextjs

  nginx:
    image: nginx:alpine
    container_name: nginx
    ports:
      - "81:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - nextjs